export interface Merchant {
  store: string;
  cardOffer: string;
  rakutenPoints: string;
  lastUpdated?: string;
}

export interface Card {
  id: string;
  name: string;
  shortName: string;
  color: string;
  sheetName: string;
  merchants: Merchant[];
}

// Edit name/endDate here to repurpose for future promo events.
export const PROMO_EVENT = {
  name: 'Big Give Week',
  endDate: '2026-05-11T23:59:59',
};

export const SITE_META = {
  lastUpdated: 'May 7, 2026 at 7:30 AM PST',
  updateFrequency: 'daily',
};

export const STATIC_CARDS: Card[] = [
  {
    id: 'chase',
    name: 'CSP',
    shortName: 'CSP',
    color: 'chase',
    sheetName: 'Chase Sapphire',
    merchants: [
      { store: 'Viator', cardOffer: '8% cash back', rakutenPoints: '15x points' },
      { store: 'Adidas', cardOffer: '$20 cash back', rakutenPoints: 'up to 15x points' },
      { store: 'Therabody', cardOffer: '15% cash back', rakutenPoints: '15x points' },
      { store: "Lands' End", cardOffer: '10% cash back', rakutenPoints: '15x points' },
      { store: 'iHerb', cardOffer: '10% cash back', rakutenPoints: '15x points' },
      { store: 'Airalo', cardOffer: '15% cash back', rakutenPoints: '15x points' },
      { store: 'AG1', cardOffer: '25% cash back', rakutenPoints: '15x points' },
      { store: 'Redken', cardOffer: '15% cash back', rakutenPoints: '15x points' },
      { store: 'Ancestry', cardOffer: '10% cash back', rakutenPoints: '15x points' },
      { store: 'Tommy John', cardOffer: '15% cash back', rakutenPoints: '15x points' },
      { store: 'KiwiCo', cardOffer: '10% cash back', rakutenPoints: '15x points' },
      { store: 'Tory Burch', cardOffer: '5% cash back', rakutenPoints: '15x points' },
      { store: 'ALDO', cardOffer: '8% cash back', rakutenPoints: '15x points' },
      { store: 'Maurices', cardOffer: '15% cash back', rakutenPoints: '15x points' },
      { store: 'Thrive Causemetics', cardOffer: '12% cash back', rakutenPoints: '15x points' },
      { store: 'VistaPrint', cardOffer: '10% cash back', rakutenPoints: '15x points' },
      { store: 'Eberjey', cardOffer: '10% cash back', rakutenPoints: '15x points' },
      { store: 'LegalZoom', cardOffer: '20% cash back', rakutenPoints: '15x points' },
      { store: 'Teleflora', cardOffer: '10% cash back', rakutenPoints: '15x points' },
      { store: 'Charles Tyrwhitt', cardOffer: '$25 cash back', rakutenPoints: '15x points' },
      { store: 'Lindt', cardOffer: '10% cash back', rakutenPoints: '15x points' },
      { store: 'Moen', cardOffer: '10% cash back', rakutenPoints: '15x points' },
      { store: 'Shop LC', cardOffer: '15% cash back', rakutenPoints: '15x points' },
      { store: 'NOBULL', cardOffer: '$20 cash back', rakutenPoints: '15x points' },
      { store: 'Straight Talk', cardOffer: '15% cash back', rakutenPoints: '1,500 points' },
      { store: 'Babbel', cardOffer: '15% cash back', rakutenPoints: '15x points' },
      { store: 'MERIT Beauty', cardOffer: '10% cash back', rakutenPoints: '15x points' },
      { store: 'Yale Locks', cardOffer: '10% cash back', rakutenPoints: '15x points' },
      { store: 'Little Spoon', cardOffer: '10% cash back', rakutenPoints: '15x points' },
      { store: 'Liquid IV', cardOffer: '15% cash back', rakutenPoints: '15x points' },
      { store: 'SIXT', cardOffer: '15% cash back', rakutenPoints: '15x points' },
      { store: 'BODi', cardOffer: '10% cash back', rakutenPoints: '15x points' },
      { store: 'Trafalgar', cardOffer: '$200 cash back', rakutenPoints: '45,000 points' },
    ],
  },
  {
    id: 'united',
    name: 'United',
    shortName: 'United',
    color: 'united',
    sheetName: 'United',
    merchants: [
      { store: "Lands' End", cardOffer: '10% cash back', rakutenPoints: '15x points' },
      { store: 'Mattress Firm', cardOffer: '3% cash back', rakutenPoints: 'up to 15x points' },
      { store: 'iHerb', cardOffer: '10% cash back', rakutenPoints: '15x points' },
      { store: 'Therabody', cardOffer: '15% cash back', rakutenPoints: '15x points' },
      { store: 'Ancestry', cardOffer: '10% cash back', rakutenPoints: '15x points' },
      { store: 'Redken', cardOffer: '15% cash back', rakutenPoints: '15x points' },
      { store: 'Tommy John', cardOffer: '15% cash back', rakutenPoints: '15x points' },
      { store: 'Tory Burch', cardOffer: '5% cash back', rakutenPoints: '15x points' },
      { store: 'Maurices', cardOffer: '15% cash back', rakutenPoints: '15x points' },
      { store: 'Liquid IV', cardOffer: '15% cash back', rakutenPoints: '15x points' },
      { store: 'Lindt', cardOffer: '10% cash back', rakutenPoints: '15x points' },
      { store: 'ALDO', cardOffer: '8% cash back', rakutenPoints: '15x points' },
      { store: 'Thrive Causemetics', cardOffer: '12% cash back', rakutenPoints: '15x points' },
      { store: 'Shop LC', cardOffer: '15% cash back', rakutenPoints: '15x points' },
      { store: 'Eberjey', cardOffer: '10% cash back', rakutenPoints: '15x points' },
      { store: 'KiwiCo', cardOffer: '10% cash back', rakutenPoints: '15x points' },
      { store: 'NOBULL', cardOffer: '$20 cash back', rakutenPoints: '15x points' },
      { store: 'At Home', cardOffer: '15% cash back', rakutenPoints: '15x points' },
      { store: 'Teleflora', cardOffer: '10% cash back', rakutenPoints: '15x points' },
      { store: 'LegalZoom', cardOffer: '20% cash back', rakutenPoints: '15x points' },
      { store: 'Moen', cardOffer: '10% cash back', rakutenPoints: '15x points' },
      { store: 'Babbel', cardOffer: '15% cash back', rakutenPoints: '15x points' },
      { store: 'Straight Talk', cardOffer: '15% cash back', rakutenPoints: '1,500 points' },
      { store: 'CAKES Body', cardOffer: '10% cash back', rakutenPoints: '15x points' },
      { store: 'Little Spoon', cardOffer: '10% cash back', rakutenPoints: '15x points' },
      { store: 'MERIT Beauty', cardOffer: '10% cash back', rakutenPoints: '15x points' },
      { store: 'Yale Locks', cardOffer: '10% cash back', rakutenPoints: '15x points' },
      { store: 'VistaPrint', cardOffer: '10% cash back', rakutenPoints: '15x points' },
      { store: 'BODi', cardOffer: '10% cash back', rakutenPoints: '15x points' },
    ],
  },
  {
    id: 'hyatt',
    name: 'Hyatt',
    shortName: 'Hyatt',
    color: 'hyatt',
    sheetName: 'World of Hyatt',
    merchants: [
      { store: 'Adidas', cardOffer: '$20 cash back', rakutenPoints: 'up to 15x points' },
      { store: "Lands' End", cardOffer: '10% cash back', rakutenPoints: '15x points' },
      { store: 'iHerb', cardOffer: '10% cash back', rakutenPoints: '15x points' },
      { store: 'Redken', cardOffer: '15% cash back', rakutenPoints: '15x points' },
      { store: 'AG1', cardOffer: '25% cash back', rakutenPoints: '15x points' },
      { store: 'Tommy John', cardOffer: '15% cash back', rakutenPoints: '15x points' },
      { store: 'KiwiCo', cardOffer: '10% cash back', rakutenPoints: '15x points' },
      { store: 'LegalZoom', cardOffer: '20% cash back', rakutenPoints: '15x points' },
      { store: 'Teleflora', cardOffer: '10% cash back', rakutenPoints: '15x points' },
      { store: 'BODi', cardOffer: '10% cash back', rakutenPoints: '15x points' },
      { store: 'Therabody', cardOffer: '15% cash back', rakutenPoints: '15x points' },
      { store: 'Yale Locks', cardOffer: '10% cash back', rakutenPoints: '15x points' },
      { store: 'Babbel', cardOffer: '15% cash back', rakutenPoints: '15x points' },
      { store: 'Moen', cardOffer: '10% cash back', rakutenPoints: '15x points' },
      { store: 'Tory Burch', cardOffer: '5% cash back', rakutenPoints: '15x points' },
      { store: 'ALDO', cardOffer: '8% cash back', rakutenPoints: '15x points' },
      { store: 'Lindt', cardOffer: '10% cash back', rakutenPoints: '15x points' },
      { store: 'Maurices', cardOffer: '15% cash back', rakutenPoints: '15x points' },
      { store: 'Liquid IV', cardOffer: '15% cash back', rakutenPoints: '15x points' },
      { store: 'VistaPrint', cardOffer: '10% cash back', rakutenPoints: '15x points' },
      { store: 'Little Spoon', cardOffer: '10% cash back', rakutenPoints: '15x points' },
      { store: 'MERIT Beauty', cardOffer: '10% cash back', rakutenPoints: '15x points' },
      { store: 'NOBULL', cardOffer: '$20 cash back', rakutenPoints: '15x points' },
      { store: 'Eberjey', cardOffer: '10% cash back', rakutenPoints: '15x points' },
      { store: 'Shop LC', cardOffer: '15% cash back', rakutenPoints: '15x points' },
      { store: 'CAKES Body', cardOffer: '10% cash back', rakutenPoints: '15x points' },
    ],
  },
  {
    id: 'amex',
    name: 'AP',
    shortName: 'AP',
    color: 'amex',
    sheetName: 'Amex',
    merchants: [
      { store: 'Ray-Ban', cardOffer: 'Spend $175+, earn $35 back, up to 2x (total $70)', rakutenPoints: 'up to 15x points' },
      { store: 'Expedia', cardOffer: 'Earn 10% back on prepaid hotels, up to $125', rakutenPoints: 'up to 15x points' },
      { store: 'Aldo', cardOffer: 'Earn 10% back, up to $14', rakutenPoints: '15x points' },
      { store: 'Sunglass Hut', cardOffer: 'Spend $200+, earn $30 back', rakutenPoints: 'up to 15x points' },
      { store: 'Oakley', cardOffer: 'Spend $150+, earn $30 back, up to 2x (total $60)', rakutenPoints: 'up to 15x points' },
      { store: 'AT&T Wireless', cardOffer: 'Spend $65+, earn $50 back (new customers only)', rakutenPoints: 'up to 6,500 points' },
      { store: '1800Flowers', cardOffer: 'Spend $50+, earn $15 back, up to 4x (total $60)', rakutenPoints: '15x points' },
      { store: 'Kay Jewelers', cardOffer: 'Spend $500+, earn $100 back', rakutenPoints: '15x points' },
      { store: 'Straight Talk', cardOffer: 'Spend $45+, earn $20 back', rakutenPoints: '1,500 points' },
      { store: 'Soma', cardOffer: 'Spend $110+, earn $20 back', rakutenPoints: '15x points' },
      { store: 'Zales', cardOffer: 'Spend $500+, earn $100 back', rakutenPoints: '15x points' },
      { store: 'AG1', cardOffer: 'Spend $75+, earn $25 back', rakutenPoints: '15x points' },
      { store: 'Glossier', cardOffer: 'Spend $65+, earn $15 back', rakutenPoints: '15x points' },
      { store: 'ContactsDirect', cardOffer: 'Spend $100+, earn $20 back', rakutenPoints: '18x points' },
      { store: 'Barefoot Dreams', cardOffer: 'Spend $150+, earn $30 back', rakutenPoints: '15x points' },
      { store: 'Ancestry', cardOffer: 'Earn 20% back, up to $100', rakutenPoints: '15x points' },
      { store: 'Perricone MD', cardOffer: 'Spend $125+, earn $25 back', rakutenPoints: '15x points' },
      { store: 'Moen', cardOffer: 'Earn 10% back, up to $50', rakutenPoints: '15x points' },
      { store: 'Teleflora', cardOffer: 'Spend $30+, earn $18 back, up to 10x (total $180)', rakutenPoints: '15x points' },
      { store: 'NOBULL', cardOffer: 'Spend $150+, earn $30 back', rakutenPoints: '15x points' },
      { store: 'Banter by Piercing Pagoda', cardOffer: 'Spend $100+, earn $20 back', rakutenPoints: '15x points' },
      { store: 'LensCrafters', cardOffer: 'Spend $200+, earn $40 back', rakutenPoints: '15x points' },
    ],
  },
];
